# -*- coding: utf-8 -*-
{
    'name' : 'Library Management Test',
    'version' : '1.0.0',
    'summary': 'library management here',
    'sequence':-100,
    'author':'Rahul Gautam',
    'description': """this is the library management setting here """,
    'category': 'Accounting/Accounting',
   # 'website': 'https://www.odoo.com/app/invoicing',
    'depends': ['mail','product'],
    'data': [
            'security/ir.model.access.csv',
            'data/student_tag_data.xml',
            'data/student.tag.csv',
            'data/sequence_data.xml',
            'data/pro_sequence.xml',
            'wizard/cancels.xml',
            'views/determin_view.xml',
            'views/menu.xml',
            'views/student_view.xml',
            'views/enrollment_view.xml',
            'views/male_student_view.xml',
            'views/female_student_view.xml',
            'views/res_config_settings_views.xml',
            'views/student_tag.xml',
            'views/operations.xml'
        ],
    'demo': [],
    'installable': True,
    'application': True,
   # 'post_init_hook': '_account_post_init',
    'assets': {},
    'license': 'LGPL-3',
}
